<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskbarGroups.Core\TaskbarGroups.Core.csproj" />
    <ProjectReference Include="..\TaskbarGroups.Data\TaskbarGroups.Data.csproj" />
  </ItemGroup>

</Project>