using System;
using System.IO;
using System.Text.Json;

namespace TaskbarGroups.Discovery.PwaDiscovery
{
    /// <summary>An installed web application's manifest.</summary>
    public sealed class PwaEntry
    {
        public string Name { get; set; } = string.Empty;

        public string? StartUrl { get; set; }

        /// <summary>Absolute path of the largest declared icon, when present.</summary>
        public string? IconPath { get; set; }

        public string Display { get; set; } = string.Empty;
    }

    /// <summary>
    /// Reads the manifest an installed browser web app leaves on disk.
    /// </summary>
    /// <remarks>
    /// These files are generated by the browser and are not a published format, so
    /// the reader is strictly total: any parse failure yields null and the app is
    /// simply not offered. The file is size-limited before it is read so a
    /// pathological entry cannot stall a discovery pass.
    /// </remarks>
    internal static class WebAppManifest
    {
        private const long MaxManifestBytes = 512 * 1024;

        internal static PwaEntry? Read(string manifestPath)
        {
            try
            {
                var info = new FileInfo(manifestPath);
                if (!info.Exists || info.Length > MaxManifestBytes) return null;

                using FileStream stream = new FileStream(manifestPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                using JsonDocument document = JsonDocument.Parse(stream);

                JsonElement root = document.RootElement;
                if (root.ValueKind != JsonValueKind.Object) return null;

                var entry = new PwaEntry
                {
                    Name = ReadString(root, "name") ?? ReadString(root, "short_name") ?? string.Empty,
                    StartUrl = ReadString(root, "start_url"),
                    Display = ReadString(root, "display") ?? string.Empty
                };

                if (root.TryGetProperty("icons", out JsonElement icons) && icons.ValueKind == JsonValueKind.Array)
                {
                    string? best = null;
                    long bestSize = -1;

                    foreach (JsonElement icon in icons.EnumerateArray())
                    {
                        string? src = ReadString(icon, "src");
                        if (string.IsNullOrWhiteSpace(src)) continue;

                        long size = ReadSize(icon);
                        if (size > bestSize)
                        {
                            bestSize = size;
                            best = src;
                        }
                    }

                    if (best != null)
                    {
                        string candidate = Path.Combine(
                            Path.GetDirectoryName(manifestPath) ?? string.Empty,
                            best.Replace('/', Path.DirectorySeparatorChar));

                        if (File.Exists(candidate)) entry.IconPath = candidate;
                    }
                }

                return entry;
            }
            catch (JsonException)
            {
                return null;
            }
            catch (IOException)
            {
                return null;
            }
            catch (UnauthorizedAccessException)
            {
                return null;
            }
        }

        private static string? ReadString(JsonElement element, string property)
        {
            if (!element.TryGetProperty(property, out JsonElement value)) return null;
            return value.ValueKind == JsonValueKind.String ? value.GetString() : null;
        }

        private static long ReadSize(JsonElement element)
        {
            if (!element.TryGetProperty("sizes", out JsonElement value)) return 0;

            if (value.ValueKind == JsonValueKind.Number) return value.GetInt64();

            if (value.ValueKind == JsonValueKind.String)
            {
                string text = value.GetString() ?? string.Empty;
                int x = text.IndexOf('x');
                if (x > 0 && long.TryParse(text.Substring(0, x), out long width)) return width;
            }

            return 0;
        }
    }
}