//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskbarGroups.App.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("TaskbarGroups.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Add", resourceCulture); }
        }

        internal static System.Drawing.Bitmap AddGray
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("AddGray", resourceCulture); }
        }

        internal static System.Drawing.Bitmap AddIconGray
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("AddIconGray", resourceCulture); }
        }

        internal static System.Drawing.Bitmap AddIconWhite
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("AddIconWhite", resourceCulture); }
        }

        internal static System.Drawing.Bitmap AddShortcut
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("AddShortcut", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Error
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Error", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumDown
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumDown", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumDownGray
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumDownGray", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumDownWhite
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumDownWhite", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumUp
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumUp", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumUpGray
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumUpGray", resourceCulture); }
        }

        internal static System.Drawing.Bitmap NumUpWhite
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("NumUpWhite", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Subtract
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Subtract", resourceCulture); }
        }
    }
}